instagram_clone/instagram_clone/urls.py
from authy.views import UserProfile, follow
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('authy.urls')),
    path('post/', include('post.urls')),
    path('direct/', include('direct.urls')),
    path('notifications/', include('notifications.urls')),
    path('<username>/saved', UserProfile, name = 'profilefavorite'),
    path('<username>/', UserProfile, name = 'profile'),
    path('<username>/follow/<option>', follow, name = 'follow'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instagram_clone/notifications/urls.py
from django.urls import path
from notifications.views import showNotifications, delete_notification

urlpatterns = [
    path('', showNotifications, name='show_notifications'),
    path('<notification_id>/delete', delete_notification, name='delete_notification'),
]

instagram_clone/post/urls.py
from django.urls import path
from post.views import index, NewPost, PostDetails, tags, like, favorite

urlpatterns = [
    path('', index, name='index'),
    path('new_post/', NewPost, name = 'newPost'),
    path('<uuid:post_id>/', PostDetails, name='postdetails'),
    path('tag/<slug:tag_slug>', tags, name='tags'),
    path('<uuid:post_id>/like', like, name = 'postlike'),
    path('<uuid:post_id>/favorite', favorite, name = 'postfavorite')
]

instagram_clone/notifications/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class notification(models.Model):
    NOTIFICATION_TYPES = ((1, 'Like'), (2, 'Comment'), (3, 'Follow'))

    post = models.ForeignKey('post.Post', on_delete=models.CASCADE, related_name='notification_post', null=True, blank=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification_from_user')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='notification_to_user')
    notification_type = models.IntegerField(choices=NOTIFICATION_TYPES)
    text_preview = models.CharField(max_length=90, blank=True)
    date = models.DateTimeField(auto_now_add=True)
    is_seen = models.BooleanField(default=False)

instagram_clone/authy/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Profile

def ForbiddenUsers(value):
	forbidden_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root',
	'email', 'user', 'join', 'sql', 'static', 'python', 'delete']
	if value.lower() in forbidden_users:
		raise ValidationError('Invalid name for user, this is a reserverd word.')

def InvalidUser(value):
	if '@' in value or '+' in value or '-' in value:
		raise ValidationError('This is an Invalid user, Do not user these chars: @ , - , + ')

def UniqueEmail(value):
	if User.objects.filter(email__iexact=value).exists():
		raise ValidationError('User with this email already exists.')

def UniqueUser(value):
	if User.objects.filter(username__iexact=value).exists():
		raise ValidationError('User with this username already exists.')

class SignupForm(forms.ModelForm):
	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'input is-medium', 'placeholder':'Username'}), max_length=30, required=True,)
	email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'input is-medium', 'placeholder':'Email Address'}), max_length=100, required=True,)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium', 'placeholder':'Password'}))
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium', 'placeholder':'Confirm Password'}), required=True, label="Confirm your password.")
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'First name'}), max_length=50, required=True)
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'Last name'}), max_length=50, required=True)


	class Meta:

		model = User
		fields = ('username', 'email', 'password')

	def __init__(self, *args, **kwargs):
		super(SignupForm, self).__init__(*args, **kwargs)
		self.fields['username'].validators.append(ForbiddenUsers)
		self.fields['username'].validators.append(InvalidUser)
		self.fields['username'].validators.append(UniqueUser)
		self.fields['email'].validators.append(UniqueEmail)

	def clean(self):
		super(SignupForm, self).clean()
		password = self.cleaned_data.get('password')
		confirm_password = self.cleaned_data.get('confirm_password')

		if password != confirm_password:
			self._errors['password'] = self.error_class(['Passwords do not match. Try again'])
		return self.cleaned_data

class ChangePasswordForm(forms.ModelForm):
	id = forms.CharField(widget=forms.HiddenInput())
	old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Old password", required=True)
	new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="New password", required=True)
	confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input is-medium'}), label="Confirm new password", required=True)

	class Meta:
		model = User
		fields = ('id', 'old_password', 'new_password', 'confirm_password')

	def clean(self):
		super(ChangePasswordForm, self).clean()
		id = self.cleaned_data.get('id')
		old_password = self.cleaned_data.get('old_password')
		new_password = self.cleaned_data.get('new_password')
		confirm_password = self.cleaned_data.get('confirm_password')
		user = User.objects.get(pk=id)
		if not user.check_password(old_password):
			self._errors['old_password'] =self.error_class(['Old password do not match.'])
		if new_password != confirm_password:
			self._errors['new_password'] =self.error_class(['Passwords do not match.'])
		return self.cleaned_data

class EditProfileForm(forms.ModelForm):
	picture = forms.ImageField(required=False)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'First name'}), max_length=50, required=False)
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'Last name'}), max_length=50, required=False)
	location = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'Location'}), max_length=25, required=False)
	url = forms.URLField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'Website'}), max_length=60, required=False)
	profile_info = forms.CharField(widget=forms.Textarea(attrs={'class':'input is-medium', 'placeholder':'Add a Bio'}), max_length=260, required=False)

	class Meta:
		model = Profile
		fields = ('picture', 'first_name', 'last_name', 'location', 'url', 'profile_info')

instagram_clone/post/forms.py
from django import forms
from post.models import Post

from django.forms import ClearableFileInput

class NewPostForm(forms.ModelForm):
    content = forms.FileField(widget=ClearableFileInput(attrs={'multiple':True}), required=True)
    caption = forms.CharField(widget=forms.Textarea(attrs={'class':'input is-medium', 'placeholder':'Add a Caption'}), required=True)
    tags = forms.CharField(widget=forms.TextInput(attrs={'class':'input is-medium', 'placeholder':'Add tags separated by Commas'}), required=False)

    class Meta:
        model = Post
        fields = ('content', 'caption','tags') 

instagram_clone/notifications/views.py
from django.shortcuts import redirect
from django.template import loader
from django.http import HttpResponse
from notifications.models import notification
# Create your views here.

def showNotifications(request):
    user = request.user
    notifications = notification.objects.filter(user = user).order_by('-date')
    notifications.update(is_seen=True)
    template = loader.get_template('notifications.html')


    context = {
        'notifications': notifications,
    }

    return HttpResponse(template.render(context, request))

def delete_notification(request, notification_id):
    user = request.user
    notification.objects.filter(id=notification_id, user=user).delete()
    return redirect('show_notifications')


def count_notifications(request):
    notification_count = 0
    if request.user.is_authenticated:
        notification_count = notification.objects.filter(user=request.user, is_seen=False).count()

    return {'notification_count':notification_count}

instagram_clone/instagram_clone/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Instagram</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>

    <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="navbar-brand">
            <a class="navbar-item" href="{% url 'index' %}">
                <img src="{% static 'img/instagram_black.png' %}">
            </a>

            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a href="{% url 'index' %}" class="navbar-item">
                    <span class="material-icons">home</span>
                    Home
                </a>

                <a class="navbar-item">
                    <span class="material-icons">explore</span>
                    Explore
                </a>

                <a class="navbar-item" href="{% url 'show_notifications' %}">
                    <span class="material-icons">
                        notifications
                    </span>
                    Notifications
                    {% if notification_count %}
                    <span class="badge">{{ notification_count }}</span>
                    {% endif %}
                </a>

                <a class="navbar-item" href="{% url 'inbox' %}">
                    <span class="material-icons">
                        inbox
                    </span>
                    Inbox
                    {% if directs_count %}
                    <span class="badge">{{ directs_count }}</span>
                    {% endif %}
                </a>

                <a class="navbar-item" href="{% url 'profile' request.user %}">
                    <span class="material-icons">
                        face
                    </span>
                    {% if request.user.is_authenticated %}
                    <strong>{{ request.user }}</strong>
                    {% else %}
                    Profile
                    {% endif %}

                </a>

                <a href="{% url 'newPost' %}" class="navbar-item">
                    <span class="material-icons">
                        perm_media
                    </span>
                    New Post
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        Settings
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url 'change_password' %}">
                            Change Password
                        </a>
                        <a class="navbar-item">
                            Contact
                        </a>
                        <a class="navbar-item">
                            Report an issue
                        </a>
                        <hr class="navbar-divider">
                        <a href="{% url 'logout' %}" class="navbar-item">
                            Log Out
                        </a>
                    </div>
                </div>
            </div>


        </div>
    </nav>
    {% block banner %}
    {% endblock %}

    <section class="section">
        <div class="container">

            {% block content %}
            {% endblock %}

            {% block pagination %}
            {% endblock %}


        </div>
    </section>
</body>
<script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
<script src="{% static 'js/init.js' %}"></script>
<script src="{% static 'js/slider.js' %}"></script>

</html>

instagram_clone/instagram_clone/templates/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="columns is-mobile has-text-centered">
    <div class="column is-half is-offset-one-quarter">

        <div class="card">
            <div class="card-content">



                <form method="post" action="" role="form">
                    {% csrf_token %}
                    {{ form.id }}
                    <h3 class="title is-3">Change password</h3>

                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Old Password</label>
                            {{ form.old_password }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">New password</label>
                            {{ form.new_password }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Re-type Password</label>
                            {{ form.confirm_password }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                        </div>
                    </div>
                    <div class="field">
                        <p class="control">
                            <button class="button is-success" type="submit" name="action">
                                Change Password
                            </button>
                        </p>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

instagram_clone/instagram_clone/templates/change_password_done.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>

<body>

    <div class="section">
        <div class="contained">
            <div class="columns is-mobile has-text-centered">
                <div class="column is-half is-offset-one-quarter">

                    <div class="card">
                        <div class="card-content">


                            <br>
                            <br>
                            <div class="col s12 center-align">
                                <i class="large material-icons green-text">check_circle</i>
                            </div>
                            <h3 class="title is-3">
                                Your password has been succesfully changed
                            </h3>
                            <br>
                            <br>


                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>

</body>

</html>

instagram_clone/instagram_clone/templates/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="columns is-mobile">
    <div class="column is-half is-offset-one-quarter">

        <div class="card">
            <div class="card-content">



                <form method="post" action="" enctype="multipart/form-data" role="form">
                    <h3 class="title is-3 has-text-centered">Edit Profile</h3>

                    {% csrf_token %}

                    <div class="field">
                        <label class="label is-medium">Upload Profile picture</label>
                        <div class="file is-info has-name">
                            <label class="file-label">
                                <input class="file-input" type="file" name="picture" id="id_picture" accept="image/*">
                                <span class="file-cta">
                                    <span class="file-icon">
                                        <i class="fas fa-upload"></i>
                                    </span>
                                    <span class="file-label">
                                        Choose file
                                    </span>
                                </span>
                                <span class="file-name">
                                    No file Chosen
                                </span>
                            </label>
                        </div>
                    </div>


                    <script>
                        const fileInput = document.querySelector('input[type=file]');
                        fileInput.onchange = () => {
                            if (fileInput.files.length > 0) {
                                const fileName = document.querySelector('.file-name');
                                fileName.textContent = fileInput.files[0].name;
                            }
                        }
                    </script>

                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">First name</label>
                            {{ form.first_name }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Last Name</label>
                            {{ form.last_name }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Location</label>
                            {{ form.location }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Website</label>
                            {{ form.url }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Profile Info</label>
                            {{ form.profile_info }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="row">
                        <div class="col s12">
                            <span style="color: red; font-weight: bold;">{{ form.errors }}</span>
                        </div>
                    </div>
                    <div class="field">
                        <p class="control">
                            <button class="button is-success" type="submit" name="action">
                                Update Profile
                            </button>
                        </p>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

instagram_clone/instagram_clone/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="columns is-mobile is-centered">
    <div class="column">

        {% for post_item in post_items %}
        <div class="card">
            {% if post_item.content.first.file.name|slice:'-3:' in "jpgpng" %}
            <div class="card-image">
                <div class="slideshow-container">
                    <figure class="image">
                        <a href="{{ post_item.get_absolute_url }}">
                            <img src="{{ post_item.content.first.file.url }}" alt="Image">
                        </a>
                    </figure>
                </div>
            </div>
            {% else %}
            <div class="card-image">
                <div class="slideshow-container">
                    <figure class="image">
                        <a href="{{ post_item.get_absolute_url }}">
                            <video controls="controls" preload="metadata" style="width:100%">
                                <source src="{{ post_item.content.first.file.url }}#t=0.5" type="video/mp4">
                        </a>
                    </figure>
                </div>
            </div>
            {% endif %}
            <div class="card-content">
                <div class="media">
                    <div class="media-left">
                        <figure class="image is-48x48">
                            {% if post_item.user.profile.picture %}
                            <img src="{{ post_item.user.profile.picture.url }}" alt="mage">
                            {% else %}
                            <img src="{% static 'img/default.png' %}" alt="mage">
                            {% endif %}
                        </figure>
                    </div>
                    <div class="media-content">
                        <p class="title is-4">
                            <a href="{% url 'profile' post_item.user %}">
                                {{ post_item.user.first_name }}

                                {{ post_item.user.last_name }}
                            </a>
                        </p>
                        <p class="subtitle is-6">
                            <a href="{% url 'profile' post_item.user %}">
                                @{{ post_item.user.username }}
                            </a>
                        </p>

                        {{ post_item.caption }}
                        <p>
                            {% for tag in post_item.tags.all %}
                            <a href="{{ tag.get_absolute_url }}">#{{ tag }}</a>
                            {% endfor %}
                        </p>
                        <br>
                        <strong><small>{{ post_item.posted }}</small></strong>
                    </div>
                    {% if post_item.id in liked_posts %}

                    <div class="media-right">
                        <a href="{% url 'postlike' post_item.id %}">
                            <i class="material-icons has-text-danger">favorite</i>
                            <p class="has-text-danger">{{ post_item.likes }} Likes</p>
                        </a>
                    </div>
                    {% else %}
                    <div class="media-right">
                        <a href="{% url 'postlike' post_item.id %}">
                            <i class="material-icons has-text-danger">favorite_border</i>
                            <p class="has-text-danger">{{ post_item.likes }} Likes</p>
                        </a>
                    </div>
                    {% endif %}
                </div>

            </div>
        </div>
        <br>
        {% endfor %}

    </div>
</div>
{% endblock %}

instagram_clone/instagram_clone/templates/newpost.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="columns is-mobile">
    <div class="column is-half is-offset-one-quarter">

        <div class="card">
            <div class="card-content">




                <form method="post" action="" enctype="multipart/form-data" role="form">
                    {% csrf_token %}
                    <h3 class="title is-3 has-text-centered">New Post</h3>



                    <div class="field">
                        <label class="label is-medium">Upload Content</label>
                        <div class="file is-info has-name">
                            <label class="file-label">
                                <input class="file-input" multiple required type="file" name="content" id="id_content"
                                    accept="image/*,video/*">
                                <span class="file-cta">
                                    <span class="file-icon">
                                        <i class="fas fa-upload"></i>
                                    </span>
                                    <span class="file-label">
                                        Choose file
                                    </span>
                                </span>
                                <span class="file-name">
                                    No file Chosen
                                </span>
                            </label>
                        </div>
                    </div>


                    <script>
                        const fileInput = document.querySelector('input[type=file]');
                        fileInput.onchange = () => {
                            if (fileInput.files.length > 0) {
                                const fileName = document.querySelector('.file-name');
                                fileName.textContent = fileInput.files[0].name;
                            }
                        }
                    </script>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Caption</label>
                            {{ form.caption }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control has-icons-left">
                            <label class="label is-medium">Tags</label>
                            {{ form.tags }}
                            <span class="icon is-small is-left">
                                <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <div class="field">
                        <p class="control">
                            <button class="button is-success" type="submit" name="action">
                                Create Post
                            </button>
                        </p>
                    </div>

                </form>





            </div>
        </div>
    </div>
</div>

{% endblock %}

instagram_clone/instagram_clone/templates/tag.html
{% extends 'base.html' %}
{% load static %}

{% block banner %}

<section class="hero is-primary">
    <div class="hero-body">
        <p style="font-size: 90px;" class="title">
            #{{ tag.title }}
        </p>
    </div>
</section>
{% endblock %}

{% block content %}
<div class="columns is-mobile is-multiline is-centered">
    {% for post in posts %}

    <div class="column is-one-quarter">
        <div class="box">
            <figure class="image is-264x264">
                <a href="{{ post.get_absolute_url }}"><img src="{{ post.picture.url }}" alt="Image"></a>
            </figure>
        </div>
    </div>

    {% endfor %}
</div>
{% endblock %}